.PHONY: clean

pointerqueue:
	@chmod 755 pointerqueue.py
	@python pointerqueue.py

loctree:
	@chmod 755 loctree.py
	@python loctree.py

lcrstree:
	@chmod 755 lcrstree.py
	@python lcrstree.py

listconcat:
	@chmod 755 listconcat.py
	@python listconcat.py

traversalconvert:
	@chmod 755 traversalconvert.py
	@python traversalconvert.py

preorder:
	@chmod 755 preorder.py
	@python preorder.py

postorder:
	@chmod 755 postorder.py
	@python postorder.py

huffman:
	@chmod 755 huffman.py
	@python huffman.py

clean:
	@\rm -f *.pyc