.PHONY: clean

timing:
    @chmod 755 timing.py
	@python timing.py

arraylist:
    @chmod 755 arraylist.py
	@python arraylist.py

pointerlist:
    @chmod 755 pointerlist.py
	@python pointerlist.py

arraystack:
    @chmod 755 arraystack.py
	@python arraystack.py

pointerstack:
    @chmod 755 pointerstack.py
	@python pointerstack.py

clean:
	@\rm -f *.pyc